### ISSUE TITLE
Cannot find library nfc

### ISSUE THREAD

**Issue by KenT2** [ikelos/pynfc#15]
I am trying to install pynfc and get the error message below.
I have installed libnfc5 and with apt-get and nfc-poll works fine.

    import nfc
  File "/home/pi/newpynfc-master/src/nfc.py", line 607, in <module>
    _libs["nfc"] = load_library("nfc")
  File "/home/pi/newpynfc-master/src/nfc.py", line 367, in load_library
    raise ImportError("%s not found." % libname)
ImportError: nfc not found.

**Comment by xetum** [comment]
if you're in RPi, code to find libnfc is buggy. For a quick workaround change line 477 of nfc.py to:
`for dir in open('/etc/ld.so.conf.d/arm-linux-gnueabihf.conf')`

**Comment by KenT2** [comment]
Sorry, should have said it was on a RPi. Works wonderfully now, thanks
